### ISSUE TITLE
Github Action breaks with more than 1 argument

### ISSUE THREAD

**Issue by tomekchime** [standardnotes/brakeman-action#1]
It looks like if you specify more than one argument, Github Actions will quote the options which results in an error.

```yml
name: Brakeman
on: [ pull_request ]

jobs:
  brakeman-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Brakeman code scanning
        uses: standardnotes/brakeman-action@v1.0.0
        with:
          options: --color -q
```

Results in a command run with `presidentbeef/brakeman  "--color -q"`. The container will parse `--color -q` as a single flag and show the brakeman help dialog.
